### ISSUE TITLE
Java 질문1

### ISSUE THREAD

**Issue by opklnm102** [zpq456/myjavanote#2]
1. 오버로딩과 오버라이딩이란?
2. 추상클래스, 인터페이스란? 
3. byte와 Byte의 차이(기본내용 + 메모리 관련)

**Comment by zpq456** [comment]
####이슈2
1. 오버로딩과 오버라이딩이란?
오버로딩과 오버라이딩은 둘 다 자바에서 다형성을 지원하는
방법이다. 
오버로딩은 같은 이름의 메소드를 여러개 가지면서 매개변수의 
유형과 개수가 다르도록 하는 기술이다. 
오버라이딩은 상위 클래스가 가지고 있는 메소드를 하위 클래스가 
재정의해서 사용하는 기술이다.
1. 추상 클래스, 인터페이스란?
   추상 클래스는 한개 이상의 추상 메소드를 가지고 있는 클래스이다.
   (추상 메소드는 선언부만 있고 본문은 없는 메소드이다.)
   추상 클래스는 추상 메소드가 구현되어 있지 않아서 인스턴스의
   생성이 불가능하고 해당 클래스를 상속 하여 추상 메소드를
   구현해야만 사용할 수 있다. 이미 구현되어 있는 메소드를
   사용하려고 해도 상속한 후에 추상 메소드들을 오버라이딩 하여
   사용하여야 한다.
   인터페이스는 추상 메소드로만 이루어진 클래스를 말하고 이를
   구현하는 자식 클래스로 하여금 모든 추상 메소드의 구현을
   강제한다.
   추상 클래스와 인터페이스는 비슷한듯 하지만 큰 차이점이 있다.
   자바는 단일상속만을 지원하기 때문에 추상 클래스를 상속받는
   클래스는 다른 클래스를 상속받지 못하게 된다. 하지만 인터페이스를
   포함하는 클래스는 다른 클래스를 상속 받을 수 있다.
   따라서 인터페이스는 다중상속의 장점을 자바에서 쓰기위해 사용하는
   것이다.
2. byte와 Byte의 차이(기본내용 + 메모리 관련)
   자바에는 C와는 다르게 Wrapper클래스가 존재한다. 이들을
   기존의 자료형과 차이를 주기 위해서 대문자로 시작하는 이름을
   가진다.(int - Integer / byte - Byte)
   이들은 프리미티브 타입의 데이터를 감싸는 역할을 하며
   자료형을 클래스처럼 사용할 수 있다. 
   boolean 자료형을 제외한 모든 부분에서 MAX(MIN)_VALUE라는
   멤버를 가진다.
   byte의 MAX는 127 MIN은 -128이다

**Comment by opklnm102** [comment]
@zpq456 시간있으면 3번은 GC관련해서 답변을 달아줄래? 좀더 깊이 가보자

**Comment by zpq456** [comment]
@opklnm102 객체타입이 아니라 일반 자료형으로 값을 받아두면 GC가 모아서 처리를 해버리기
때문에 저장을 못하게 되는데  래퍼클래스를 사용하면 이런 원시변수들도 저장이 가능하다.
래퍼클래스 자체가 원시변수들을 포장해서 객체화 시켜주는 것 때문에 GC에 의해서 처리되지
않으며 다른 객체처럼 메소드도 갖게 되고 객체형 배열에도 넣어서 사용이 가능한 강력한
능력을 가지게 되었다.   

이런것도 있었네요 ㄷㄷ 그럼 자바는 프로그래밍 할때 값들을 전부 객체화 시켜서 저장하지 않으면
가비지컬랙션이 다 지워버린다는 거죠?

**Comment by opklnm102** [comment]
@zpq456 잘 찾았네. 어디서 찾아온거?

**Comment by zpq456** [comment]
@opklnm102  구글링이요 ㅎㅎ
거기서는 Byte만 다룬게 아니라 래퍼클래스에 대해서 다룬거긴 하지만 ㅎㅎ
